name: Upload Files to Repository

on:
  push:
    branches:
      - main

jobs:
  upload_files:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: uploaded_files
          path: |
            ${{ github.workspace }}/uploaded-file/
          artifact: true
