name: Upload Files to Repository

on:
  push:
    branches:
      - main

jobs:
  upload_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: uploaded-files
          path: |
            ${{ github.workspace }}/uploaded-file/**
            ${{ github.workspace }}/uploaded-file/*.png
            ${{ github.workspace }}/uploaded-file/*.jpg
          artifact: true
