name: Upload Files to Repository

on:
  push:
    branches:
      - main

jobs:
  upload_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit
      - name: Run Streamlit app
        run: |
          streamlit run app.py
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: uploaded-files
          path: |
            ${{ github.workspace }}/uploaded-file/
          artifact: true